= DO500 Lab Environment Provisioning Guide
This guide provides all the necessary information for provisioning the classroom
environment for DO500 in AWS. All work is done in the `do500/classroom` folder.

== Dependencies
The DO500 lab environment provisioning depends upon the following projects:

- casl-ansible
+
This Red Hat Communities of Practice project provides the main playbooks for
building the OpenShift cluster. It depends on the following projects:
+
* infra-ansible
+
These playbooks create add-on infrastructure for the cluster.
+
* openshift-ansible
+
These playbooks install the OpenShift cluster.
+
* openshift-applier
+
These playbooks apply resources to the OpenShift cluster after it is built.
+


== Prerequisites
. AWS account with an IAM account enabled. You need the access and secret keys
for the account. Use the "Download CSV" button (available only during account creation) to save credentials.
. Access to the Employee SKU with redhat.com credentials.
. A registry.redhat.io service account.
. A hosted zone must be established in the AWS account. These instructions
currently assume `nextcle.com`
. The Red Hat "Gold Images" need to be added to the AWS account. see https://access.redhat.com/articles/2962171.
. A private key file for access to the instances. You may create and upload one
to your AWS account or use the glsdemo2.pem key. Contact Jim Rigsbee for the key file.

== Provisioning Steps

=== OpenShift Cluster
. Edit *env.sh*:
+
```
RHSM_USER=<subscription-manager username>
RHSM_PASSWD=<subscription-manager password>
RHSM_POOL=<subscription pool for Employee SKU>
REG_USERNAME=<registry.redhat.io service account username>
REG_TOKEN=<registry.redhat.io service account token>
```
+
. Make sure your AWS credentials CSV file (downloaded from IAM account creation page)
is located in $HOME as *aws-credentials.csv* The file contents look like this:
```
User name,Password,Access key ID,Secret access key,Console login link
bob,,AKIANNNNNNNNNNNNN,BBBBB/ccccc,https://933309984444.signin.aws.amazon.com/console
```
. Pull in playbook dependencies using Ansible Galaxy:
+
```
ansible-galaxy install -r do500-requirements.yml -p galaxy
```
+
. Edit *inventory_ocp/ec2.ini*:
+
```
regions = <region to place cloud formation in, e.g. us-east-1>
instance_filters = tag:env_id=<env_id, e.g. labs>
...
cloud_infrastructure:
   region: us-east-1   <---- Adjust accordingly, make it match ec2.ini values
   image_name: ami-0d70a070    <--- This is unique for your account, Red Hat Gold AMI for RHEL 7.5
   masters:
     count: 1 <--- usually 1
     flavor: m4.large  <---- this should be sufficient
     zones:
     - us-east-1a  <--- Adjust accordingly
     name_prefix: master
     root_volume_size: 40
     docker_volume_size: 30
   appnodes:
     count: 2  <--- Adjust based on the size of the class
     flavor: m4.xlarge   <---- Adjust based on the size of the class for higher/lower memory requirements
     zones:
     - us-east-1a   <---- Adjust accordingly
     name_prefix: app-node
     root_volume_size: 40
     docker_volume_size: 30
   infranodes:
     count: 1    <----- usually 1
     flavor: m4.xlarge  <---- this should be sufficient
     zones:
     - us-east-1a   <----- Adjust accordingly
     name_prefix: infra-node
     root_volume_size: 40
     docker_volume_size: 30
...
dns_domain: "nextcle.com"   <---- Adjust if domain registered is different for your environment
```
+
. Edit *inventory_ocp/group_vars/all.yaml*:
+
```
env_id: "labs" <-- change to a unique name. will be used in hostnames for each AWS instance
```
+
. Edit the *provision.sh* file:
+
```
  -e OPTS="-e aws_key_name=glsdemo2" -t \   <--- make sure this matches the AWS key name you uploaded
```
+
. Execute ./provision.sh.
+
This script:

- Sources the environment variables needed for various secrets.
- Creates an inventory in the galaxy/casl-ansible folder based on the entries in *inventory_ocp* using
the sample AWS inventory provided in github.
- Starts the `redhatcop/casl-ansible` container to provision, install, and configure the OpenShift cluster
using the Ansible playbooks and roles provided by `casl-ansible` and its related modules.
+


=== Identity Manager (LDAP)
. Using the AWS console, provision a t2.medium server with a DNS name of idm.<env_id>.nextcle.com.
Use the Gold Red Hat 7.5 AMI. Adjust the inventory files to match the host name.
Add Route53 records as follows adjusting the DNS name as needed:
* public zone: associate idm.<env_id>.nextcle.com with its public DNS name
* private zone: associate idm.<env_id>.nextcle.com with its private IP address (not name)
* Add a reverse DNS private zone, e.g. 1.20.10.in-addr.arpa for the VPC subnet. Add an entry for xxx.1.20.10.in-addr.arpa PTR pointing to idm.<env_id>.nextcle.com.
. Run the IDm provisioning playbook:
+
```
ansible-playbook -i inventory_idm/ galaxy/casl-ansible/galaxy/infra-ansible/playbooks/provision-idm/idm.yml
```
+
NOTE: I had to comment out the import_playbook: dns.yml in idm.yml playbook so that it
does not try to create DNS records for the AWS environment.
. Add stanza to */etc/origin/master/master-config.yaml* for identityProvider.
See *master-config.yaml.ldap* for specific settings.
. Add user accounts via https://idm.<env_id>.nextcle.com. Reset passwords on each account.
+
NOTE: There is a playbook to do this but I could not get it to work.
+
. Restart the master api and controllers. On master.<env_id>.nextcle.com:
+
```
  /usr/local/bin/master-restart api
  /usr/local/bin/master-restart controllers
```
+
. You should now be able to login with LDAP credentials from IdM:
+
```
oc login -u username -p password https://idm.<env_id>.nextcle.com
```
+


=== TO DO List
. Install Gitlab on cluster and tie to IdM.
. Provision user accounts on IdM.
. Reconcile this approach to building classroom with GPTE agnostic deployer.
+
NOTE: We have been given permission to use this one-off method for DO500.
+
